### ISSUE TITLE
Wrong overall tests time

### ISSUE THREAD

**Issue by nbasov** [mmotkina/mocha-parallel-tests#23]
Standard reporter outputs wrong overall test time

```
  525 passing (6s)
  13 pending


real	1m21.795s
user	0m41.096s
sys	0m4.608s
```

It reports 6s, but real time were about 1.5 min.

**Comment by 1999** [comment]
Hm... I think this can be fixed. Would you like to fix this error in PR or can i fix it myself?

**Comment by nbasov** [comment]
I spent some time figuring out how to fix but with no result yet. It would be great if you fix it.

**Comment by 1999** [comment]
@nbasov do you use `--max-parallel` option in your tests?

**Comment by nbasov** [comment]
@1999 thank you! Works great!

```
  525 passing (1m)
  13 pending

real	1m22.933s
user	0m41.240s
sys	    0m4.648s
```

Yes, i am using --max-parallel 10 since I make calls to API on limited cluster.

**Comment by 1999** [comment]
Nice. If you don't mind I will postpone publishing of the new version for 1 week.

**Comment by nbasov** [comment]
Sure, no problem.
