### ISSUE TITLE
Requires tests in separate files?

### ISSUE THREAD

**Issue by gaggle** [mmotkina/mocha-parallel-tests#33]
Hi,

Just to be sure I understand, to use this library the tests needs to be in separate files? Which I assume means there's no way to generate suites at runtime that all run in parallel? I'm trying to parallelize a dynamically generated browser-matrix into Sauce Labs.

**Comment by 1999** [comment]
Currently every suite needs to be located inside separate files, you're right. Can you post an example of such dynamically generated suite?

**Comment by gaggle** [comment]
Sure, here I generate test cases: https://github.com/gaggle/gaggle/blob/master/test/ui/index.test.js

It's basically this:

    describe("foo", function () {
      _.map(getBrowsers(), function (browser) {
        _.map(getResolutions(), function (resolution) {
          it("bar", function () {
            // Selenium test logic
          })
        })
      })
    })

I wanted to parallelise that and came across this library as a likely candidate.

**Comment by 1999** [comment]
We decided that parallelising test cases is dangerous and came to parallelising of suites inside files which is quite easy. The thing you want to get can be achieved by parallelising with promises, right?
```javascript
describe("foo", () => {
	it('bar', () => {
		const testCase = (browser, resolution) => {
			// Selenium test logic
			// returns promise

			return new Promise((resolve, reject) => {
				selenium.loadUrl(..., err => {
					if (err) {
						reject(err);
						return;
					}

					assert(...);
					resolve();
				});
			});
		};

		const cases = [];
		for (let browser of getBrowsers()) {
			for (let resolution of getResolutions()) {
				cases.push(testCase(browser, resolution));
			}
		}

		return Promise.all(cases);
	});
})
```

**Comment by gaggle** [comment]
Hm, let me see if I understand. You're suggesting I "pre-calculate" the promises within a single test case, and then submit them to be run via `Promise.all`. And run the whole thing through ordinary Mocha, is that correct?

To my knowledge Promise.all does not explicitly run code in parallel though, it just runs the Promises, so I still end up waiting for each Promise to resolve since they block while their operation is ongoing. At least that's the result I get when implementing your suggestion:

```
    var cases = []
    for (var b in sauceBrowsers) {
      var browser = sauceBrowsers[b];
      for (var r in resolutions) {
        var resolution = resolutions[r]
        cases.push(testCase(browser, resolution))
      }
    }

    return Promise.all(cases)
```
(I'm not familiar with the `let foo of bar` syntax for objects and switched to `in` for my quick test)

Did I miss your point? My mental model of Selenium is that the whole thing blocks as it executes, so my next attempt when I find time is to fork the process and run a test separately like that.

**Comment by 1999** [comment]
First of all, sorry for for..of iterating of objects. I assumed that getBrowsers() returns array-like object or an array itself. This is a mistake, right.

Second: you're again right about Selenium tests being serial and 99% that my variant is not working. I noticed it only now (what was I thinking about when I was writing that, huh :( )

As for your test case. Is this what you're trying to get?
```javascript
_.map(getBrowsers(), function (browser) {
    _.map(getResolutions(), function (resolution) {
    	describe('suite', () => {
    		before(() => {
    			return createNewSession(); // webdriverio.init() for example
    		})

    		it('should do smth: ...', () => {
    			// Selenium test logic
    		})

    		after(() => {
    			return endSession(); //webdriverio.end() for example
    		})
    	})
    })
})
```

I mean: you create suites/cases on the fly and they're running in parallel even if they are all located inside one file?

**Comment by gaggle** [comment]
Yeah that's exactly right, I'd like to accomplish dynamic test cases that are run in parallel.

**Comment by 1999** [comment]
@gaggle just wanted you to know that I'm working on this problem right now.

**Comment by gaggle** [comment]
Oh awesome. If there's a branch I can help test let me know.

**Comment by 1999** [comment]
It seems like I have found a solution without even monkey-patching mocha code. I hope it will be ready for test today.

**Comment by 1999** [comment]
@gaggle please try mocha-parallel-tests@0.5.0-beta.1

**Comment by gaggle** [comment]
Oh awesome! Thank you. I don't seem to be getting parallel running though, this is what I've done:

```
"devDependencies": {
    "mocha-parallel-tests": "^0.5.0-beta.1",

"scripts": {
     "test:ui:sl": "mocha-parallel-tests test/ui",
```

The test-code itself:
```
describe("UI", function () {
  this.timeout(5 * MINUTE)
  browserMatrix(this.title).forEach((run) => {
    it(s("index-%s", run.slug), function (done) {
      console.log("Starting", this.test.title)
      setTimeout(done, 2000)
    })
  })
})
```

And the output:
```
> mocha-parallel-tests test/ui
  UI
Starting index-windows-10-chrome-1000x650
    ✓ index-windows-10-chrome-1000x650 (2006ms)
Starting index-windows-10-microsoftedge-1000x650
    ✓ index-windows-10-microsoftedge-1000x650 (2003ms)
Starting index-linux-firefox-1000x650
    ✓ index-linux-firefox-1000x650 (2003ms)
Starting index-windows-10-internet-explorer-1000x650
Starting index-os-x-10-11-safari-1000x650
    ✓ index-windows-10-internet-explorer-1000x650 (2004ms)
    ✓ index-os-x-10-11-safari-1000x650 (2002ms)
  5 passing (10s)
```
They take 10 seconds to run so they're running linearly. If you spot something I'm doing wrong let me know, super happy to help with this. Also, I've pushed a [parallel-uitests](https://github.com/gaggle/gaggle/tree/parallel-uitests) branch with the relevant changes, if you want to sync and try yourself. Should just be an `npm run test:ui:sl` to verify.

**Comment by 1999** [comment]
Yep, you're trying to get parallel running of test cases (`it(...)`) while mocha-parallel-tests runs only suites (`describe(...)`) in parallel. The reason for this is that usually you need parallel tests execution for selenium-related stuff and you just can't / don't normally parallel test cases: they are just your actions while before/after hooks are mostly used for session instantiating and terminating.

If you change your code to smth like this it should work:

```javascript
browserMatrix(this.title).forEach((run) => {
  describe(`UI for ${run.slug}`, function () {
    this.timeout(5 * MINUTE)
  
    it('index-...', function (done) {
      console.log("Starting", this.test.title)
      setTimeout(done, 2000)
    })
  })
});
```

**Comment by gaggle** [comment]
Ah okay, right, I'd missed that point. When I run fake tests it's definitely running parallel now, that's great!

This runs in just a hair over 2 seconds:
```
browserMatrix("UI").forEach((run) => {
  describe(s("UI-%s", run.slug), function () {
    this.timeout(5 * MINUTE)
    it(s("index-%s", run.slug), function () {
      return Q.delay(2000)
        .then(() => {
          console.log(this.test.title)
        })
    })
  })
})

> mocha-parallel-tests test/ui

index-windows-10-chrome-1000x650
index-windows-10-microsoftedge-1000x650
index-linux-firefox-1000x650
index-windows-10-internet-explorer-1000x650
index-os-x-10-11-safari-1000x650

  UI-windows-10-chrome-1000x650
    ✓ index-windows-10-chrome-1000x650 (2007ms)

  1 passing (2s)

  UI-windows-10-microsoftedge-1000x650
    ✓ index-windows-10-microsoftedge-1000x650 (2006ms)

  UI-linux-firefox-1000x650
    ✓ index-linux-firefox-1000x650 (2006ms)

  UI-windows-10-internet-explorer-1000x650
    ✓ index-windows-10-internet-explorer-1000x650 (2006ms)

  UI-os-x-10-11-safari-1000x650
    ✓ index-os-x-10-11-safari-1000x650 (2005ms)
```


Just as an aside, errors seems to only talk about the first test that fails:
```
      return Q.delay(2000)
        .then(() => {
          throw new Error("Stap")
        })

> mocha-parallel-tests test/ui

  UI-windows-10-chrome-1000x650
    1) index-windows-10-chrome-1000x650

  0 passing (2s)
  1 failing

  1) UI-windows-10-chrome-1000x650 index-windows-10-chrome-1000x650:
     Error: Stap
      at test/ui/index.test.js:35:17
      at _fulfilled (node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:796:13)
      at node_modules/q/q.js:604:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  UI-windows-10-microsoftedge-1000x650
    2) index-windows-10-microsoftedge-1000x650

  UI-linux-firefox-1000x650
    3) index-linux-firefox-1000x650

  UI-windows-10-internet-explorer-1000x650
    4) index-windows-10-internet-explorer-1000x650

  UI-os-x-10-11-safari-1000x650
    5) index-os-x-10-11-safari-1000x650
```
But that's pretty minor, all things considered.


Unfortunately when I use the full test logic I don't get the expected behaviour. The full test connects to Sauce Labs and [it only shows one browser visiting it](https://saucelabs.com/beta/builds/f144c675915848a691ba75d8432bba93).

If I do like this:
```
    it(s("index-%s", run.slug), function () {
      <setting up webdriver>
      console.log(this.test.title)
      return eyes.open(webdriver, run.groupname, this.test.title, res2Obj(run.res))
        .then((driver) => {
          <selenium test commands>
        })
    })
```
I get an odd output:
```
> mocha-parallel-tests test/ui

  UI-windows-10-chrome-1000x650
index-windows-10-chrome-1000x650
index-windows-10-microsoftedge-1000x650
index-linux-firefox-1000x650
index-windows-10-internet-explorer-1000x650
index-os-x-10-11-safari-1000x650
    ✓ index-windows-10-chrome-1000x650 (100889ms)

  1 passing (2m)
```
Notice the `console.log` output appears for each test, but only one test has a checkmark, so the individual tests are run but not actually run.

If I do this test instead (`console.log` moved to be within the promise):
```
    it(s("index-%s", run.slug), function () {
      <setting up webdriver>
      return eyes.open(webdriver, run.groupname, this.test.title, res2Obj(run.res))
        .then((driver) => {
          console.log(this.test.title)
          <various selenium test commands>
        })
    })
```
Then the output becomes:
```
> mocha-parallel-tests test/ui

index-windows-10-chrome-1000x650

  UI-windows-10-chrome-1000x650
    ✓ index-windows-10-chrome-1000x650 (95032ms)

  1 passing (2m)
```
That's at least _more_ as expected output, in that Sauce Labs and the output agrees that only one test ran.

I first thought promises just didn't work, the symptoms look to me like parallel running causes only one Promise to be harnessed correctly and the others are executed but not waited to be resolved. So they'd just end immediately.

But the very first example has promises and they work correctly, so, I'm not sure... I'll give it more thought.

And again thanks so much for looking into this.

**Comment by 1999** [comment]
Let me dive into the first problem first: #37
Probably we will find a solution to the whole problem then

**Comment by 1999** [comment]
@gaggle just published `0.5.0-beta.2`, please take a look.

**Comment by gaggle** [comment]
Awesome.

Let's do it. 

First, perfect output with delay:
```
      return Q.delay(1000)
        .then(() => {
          console.log(this.test.title)
        })

> mocha-parallel-tests test/ui

index-windows-10-chrome-1000x650
index-windows-10-microsoftedge-1000x650
index-linux-firefox-1000x650
index-windows-10-internet-explorer-1000x650
index-os-x-10-11-safari-1000x650

  UI-windows-10-chrome-1000x650
    ✓ index-windows-10-chrome-1000x650 (2010ms)

  UI-windows-10-microsoftedge-1000x650
    ✓ index-windows-10-microsoftedge-1000x650 (2009ms)

  UI-linux-firefox-1000x650
    ✓ index-linux-firefox-1000x650 (2009ms)

  UI-windows-10-internet-explorer-1000x650
    ✓ index-windows-10-internet-explorer-1000x650 (2009ms)

  UI-os-x-10-11-safari-1000x650
    ✓ index-os-x-10-11-safari-1000x650 (2010ms)

  5 passing (2s)
```


And likewise with error:
```

      return Q.delay(2000)
        .then(() => {
          throw new Error("ouch")
        })

> mocha-parallel-tests test/ui

  UI-windows-10-chrome-1000x650
    1) index-windows-10-chrome-1000x650

  UI-windows-10-microsoftedge-1000x650
    2) index-windows-10-microsoftedge-1000x650

  UI-linux-firefox-1000x650
    3) index-linux-firefox-1000x650

  UI-windows-10-internet-explorer-1000x650
    4) index-windows-10-internet-explorer-1000x650

  UI-os-x-10-11-safari-1000x650
    5) index-os-x-10-11-safari-1000x650

  0 passing (2s)
  5 failing

  1) UI-windows-10-chrome-1000x650 index-windows-10-chrome-1000x650:
     Error: ouch
      at test/ui/index.test.js:35:17
      at _fulfilled (node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:796:13)
      at node_modules/q/q.js:604:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  2) UI-windows-10-microsoftedge-1000x650 index-windows-10-microsoftedge-1000x650:
     Error: ouch
      at test/ui/index.test.js:35:17
      at _fulfilled (node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:796:13)
      at node_modules/q/q.js:604:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  3) UI-linux-firefox-1000x650 index-linux-firefox-1000x650:
     Error: ouch
      at test/ui/index.test.js:35:17
      at _fulfilled (node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:796:13)
      at node_modules/q/q.js:604:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  4) UI-windows-10-internet-explorer-1000x650 index-windows-10-internet-explorer-1000x650:
     Error: ouch
      at test/ui/index.test.js:35:17
      at _fulfilled (node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:796:13)
      at node_modules/q/q.js:604:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  5) UI-os-x-10-11-safari-1000x650 index-os-x-10-11-safari-1000x650:
     Error: ouch
      at test/ui/index.test.js:35:17
      at _fulfilled (node_modules/q/q.js:834:54)
      at self.promiseDispatch.done (node_modules/q/q.js:863:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:796:13)
      at node_modules/q/q.js:604:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```


But when I run the actual test suites I only get one test that runs:
```
      const webdriver = // setup
      return eyes.open(webdriver, run.groupname, this.test.title, res2Obj(run.res))

> mocha-parallel-tests test/ui

Running: index-windows-10-chrome-1000x650

  UI-windows-10-chrome-1000x650
    ✓ index-windows-10-chrome-1000x650 (3338ms)


  1 passing (3s)
```

This seems related to the `eyes.selenium` module, as soon as it's invoked the tests no longer run correctly.. It's not necessarily something on your plate, but if you have any ideas or approaches that might shed more light on the matter let me know.

**Comment by 1999** [comment]
Not necessary. Can you give me a link to your repo so I could run tests by myself?

**Comment by gaggle** [comment]
Absolutely. Sync down branch https://github.com/gaggle/gaggle/tree/parallel-uitests

Should just be `npm run test:ui:sl`. It should run five fake tests, but fails like this:

```
> mocha-parallel-tests test/ui

Running test: index-windows-10-chrome-1000x650

  UI-windows-10-chrome-1000x650
    ✓ index-windows-10-chrome-1000x650 (1998ms)

  1 passing (2s)
```

If I flip the line @ [`/test/ui/index.test.js::40`](https://github.com/gaggle/gaggle/blob/parallel-uitests/test/ui/index.test.js#L40) then all tests run correctly.

**Comment by 1999** [comment]
Investigating.

**Comment by 1999** [comment]
Strange but SauceLabs doesn't run tests: https://saucelabs.com/jobs/adb51fa7cd0f4762afbb8aef48241cc9
@gaggle

**Comment by gaggle** [comment]
I disabled all the heavy lifting, to not depend on sauce-connect and such. It also means tests don't actually run anything, they just initialise the `eyes` object. It was the minimal code I could find that wouldn't run correctly.

If you'd prefer I'm happy to enable the full functionality, so you can test with Sauce Labs + Applitools.

**Comment by gaggle** [comment]
Oh I disabled tests in the `parallel-uitests` branch, if you run from master it'll depend on sauce-connect and credentials.

**Comment by 1999** [comment]
I am a dumbass, I forgot to switch branches, everything is okay

**Comment by 1999** [comment]
All right, I finnaly figured out what's the problem. First of all `mocha-parallel-tests@0.5.0-beta.4` does run test siotes in parallel, its test is real. As for your test I noticed that you use `selenium-webdriver` to communicate with Selenium. It has a concept of flows and prevents running them in parallel:

https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/promise.js#L2020

And each of your test suites runs Eyes.open instance of `eyes.selenium` which invokes `execute` method of `selenium-webdriver`.

https://github.com/applitools/Eyes.Selenium.JavaScript/blob/master/src/Eyes.js#L82

There's also a possibility of parallel flows, currently I'm investigating into it:

https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/example/parallel_flows.js

**Comment by gaggle** [comment]
Yeah I'll look into the parallel flows, that's really interesting. And thanks for the insight, and the energy put into all this.

**Comment by 1999** [comment]
No worries, this is a really interesting engineering task. If you have any info feel free to post it here.
