### ISSUE TITLE
root-level hooks are not being called

### ISSUE THREAD

**Issue by tsdaita** [mmotkina/mocha-parallel-tests#39]
Mocha's root level hooks, ie having before/beforeEach in a different file outside of the describe are not getting called. 

tests/sample.js
```javascript
require('./base');

describe('An afterEach hook', function () {
  afterEach(function () {
    console.log('afterEach run!');
  });

  before(function () {
    console.log('before run!');
  });

  describe('in some nested contexts', function () {
    before(function () {
      console.log('nested before run!');
    });

    it('runs after this block', function () {
      console.log('nested it run!');
    });

    it('runs again after this block', function () {
      console.log('second nested it run!');
    });
  });
});
```

tests/base.js
```javascript
before(function hello() {
  console.log('base : before run!');
});
```

When executing through mocha the before function from base is called 

> %:mocha runtime/tests/sample.js 
base : before run!
  An afterEach hook
before run!
    in some nested contexts
nested before run!
nested it run!
      ✓ runs after this block
afterEach run!
second nested it run!
      ✓ runs again after this block
afterEach run!

 >2 passing (9ms)

but executing the same through mocha-parallel it seems to ignore the file.

> %: node_modules/.bin/mocha-parallel-tests tests/
  An afterEach hook
before run!
nested before run!
    in some nested contexts
nested it run!
afterEach run!
      ✓ runs after this block
second nested it run!
      ✓ runs again after this block
afterEach run!

  2 passing (27ms)
>

**Comment by 1999** [comment]
Thanks for posting issue. Will take a look at it soon.

**Comment by 1999** [comment]
Seems interesting: if you move your base.js code into sampe.js, everything works fine. Is it possible?

**Comment by 1999** [comment]
#40

**Comment by 1999** [comment]
`mocha-parallel-tests=0.5.1` has the fix @tsdaita

**Comment by tsdaita** [comment]
Hi,
Apologies for the late response. Thanks for taking a look and fixing it.
Appears this is partially fixed. When passing the individual file ( node_modules/.bin/mocha-parallel-tests tests/sample.js) it seems to work.
But if we give just the dir path (either node_modules/.bin/mocha-parallel-tests tests/ or node_modules/.bin/mocha-parallel-tests tests/*.js) it does not seem to call the root level hooks.

**Comment by 1999** [comment]
@tsdaita can you give a more detailed example? A failing test would be even better
