### ISSUE TITLE
Does not recognize `mocha.opts`

### ISSUE THREAD

**Issue by rodoabad** [mmotkina/mocha-parallel-tests#44]
I have `mocha.opts` file that requires `babel` so all my ES6 files can be transpiled. However, when using `mocha-parallel-tests`, it doesn't seem to read that file and I'm getting the `Unexpected token import` problem.

`mocha-parallel-tests test/unit`

**Comment by 1999** [comment]
Thanks for posting issue @rodoabad.
Will look at it asap.

**Comment by 1999** [comment]
@rodoabad try mocha-parallel-tests@0.5.3 version. Does it work well?

**Comment by rodoabad** [comment]
Sorry it still does not recognize `mocha.opts`.

If `mocha.opts` is in `/test`, and your testing `/test/unit/**` does it go up? Didn't have time to look at your changes, sorry.

**Comment by 1999** [comment]
It does. I made an example repo so you could also see it: https://github.com/1999/mpt-issue-44
`git clone` and `npm install` before you run tests. `mocha.opts` is located inside test/ directory while test is in test/unit/

**Comment by rodoabad** [comment]
Try it by requiring files.

Example..

```javascript
--check-leaks
--colors
--recursive
--reporter progress
--require mocha-clean
--require test/utils/babel
--require test/utils/styles-stub
--require test/utils/window-stub
--timeout 250
```

**Comment by rodoabad** [comment]
Here's the pull request - https://github.com/1999/mpt-issue-44/pull/1

**Comment by 1999** [comment]
This is another case: `mocha-parallel-tests` seems to doesn't support `--require` option now. Can you switch to `--compilers` option?

**Comment by rodoabad** [comment]
`--require` and `--compilers` does not work.

**Comment by 1999** [comment]
Well... `--compilers` should work because we use it in our tests. Can you provide an example of `--compilers` not working?

Btw you can subscribe to [this PR](https://github.com/mmotkina/mocha-parallel-tests/pull/49) to see progress on `--require`.

**Comment by rodoabad** [comment]
Wouldn't it be the same setup?

`--compilers js:test/utils/babel-register.js`

**Comment by 1999** [comment]
In my case no: https://github.com/mmotkina/mocha-parallel-tests/blob/master/test/js-compilers/index.sh#L3
Currently looking into your example.

**Comment by 1999** [comment]
`--require` option is supported in `mocha-parallel-tests@0.5.4`

**Comment by 1999** [comment]
As for `--compilers` with file passing: subscribe to [this PR](https://github.com/mmotkina/mocha-parallel-tests/pull/51)
