### ISSUE TITLE
Support for `--compilers` option

### ISSUE THREAD

**Issue by amilajack** [mmotkina/mocha-parallel-tests#53]

**Comment by amilajack** [comment]
Compilers are a pretty common part of js projects. it would be nice if this project could support them.

**Comment by 1999** [comment]
Just published `0.5.5` version. Try it please and tell whether everything is good or not @amilajack

**Comment by amilajack** [comment]
Thanks! I'll give this a go.

**Comment by amilajack** [comment]
btw does this project support mocha 3+?

**Comment by 1999** [comment]
Thanks, I knew nothing about mocha@3 until your comment. Just ran all tests with mocha@3 and everything is okay. The only problem is that mocha-parallel-tests has mocha in "dependencies". What do you think of moving mocha into peerDependencies so you could specify which mocha version you are running tests with?

**Comment by 1999** [comment]
#55

**Comment by amilajack** [comment]
I think that would be a better idea.

**Comment by amilajack** [comment]
I just tried this and it doesnt seem to work. I'm getting syntax errors from es6 code.

**Comment by 1999** [comment]
[Test says](https://github.com/mmotkina/mocha-parallel-tests/tree/master/test/js-compilers-1) that it should. Could you please provide your code, mocha-parallel-tests version and how you run your tests? A cloneable repo would be great.

**Comment by amilajack** [comment]
Sure. You can checkout the [parallel-mocha](https://github.com/amilajack/popcorn-time-desktop/tree/parallel-mocha) branch of [my project](https://github.com/amilajack/popcorn-time-desktop/tree/parallel-mocha).

**Comment by 1999** [comment]
Thanks. I discovered that the problem is in using `--require ./test/setup.js` option. Without it everything goes ok. Will look into it asap #63

**Comment by amilajack** [comment]
Thanks!
