### ISSUE TITLE
Nothing is displaying in temrinal when using own reporter

### ISSUE THREAD

**Issue by k03mad** [mmotkina/mocha-parallel-tests#75]
https://github.com/mochajs/mocha/wiki/Third-party-reporters

Trying to use own reporter.
When I ran tests with my reporter by mocha — all fine, when with mocha-parallel-tests — terminal is empty, only retries is showing.

Как повторить:
1. Взять наши регрессионные тесты
2. Положить в корень myrep.js содержащий пример выше
3. package.json — config — reporter заменить на myrep
4. Запустить один тест мокой и все тесты параллельной мокой

**Comment by 1999** [comment]
@k03mad приложи пожалуйста пример кода сюда, чтобы можно было воспроизвести. Возможно я перемудрил тут: https://github.com/mmotkina/mocha-parallel-tests/blob/master/api.js#L31

**Comment by k03mad** [comment]
Ветка customeReporter

npm run issue-mocha
npm run issue-parallel

p.s. да, в курсе, что custom пишется(

**Comment by 1999** [comment]
Занятно, но mocha-teamcity-reporter работает ок. Завтра продолжу раскопки

**Comment by 1999** [comment]
#76

**Comment by 1999** [comment]
Пофиксил в PR и вмержил. Проблема была в том, что mpt не подгружала файлик с репортером, если он был в репозитории. Временное решение - писать как-то так `--reporter ./reprter-file.js`. Как доразберусь с проблемами в мастере (где-то тест валится про время работы), опубликую новую версию

**Comment by k03mad** [comment]
👍
